- cal_id: AAMkADg5NmZmM2QwLTQ0ZGQtNDA1Zi1iZmRkLWNkMWFjZmI1NTVlNABGAAAAAAD29fpetT5CT6wPo-7_C-fEBwB-ZpLKoid3RpHGgeoSzDJmAAAAAAEGAAB-ZpLKoid3RpHGgeoSzDJmAAAAAF3SAAA=
  entities:
  - device_id: Calendar
    end_offset: 24
    name: Calendar
    start_offset: 0
    track: false
- cal_id: AAMkADg5NmZmM2QwLTQ0ZGQtNDA1Zi1iZmRkLWNkMWFjZmI1NTVlNABGAAAAAAD29fpetT5CT6wPo-7_C-fEBwB-ZpLKoid3RpHGgeoSzDJmAAAAAAEGAAB-ZpLKoid3RpHGgeoSzDJmAAAAAF3TAAA=
  entities:
  - device_id: United Kingdom holidays
    end_offset: 24
    name: United Kingdom holidays
    start_offset: 0
    track: false
- cal_id: AAMkADg5NmZmM2QwLTQ0ZGQtNDA1Zi1iZmRkLWNkMWFjZmI1NTVlNABGAAAAAAD29fpetT5CT6wPo-7_C-fEBwB-ZpLKoid3RpHGgeoSzDJmAAAAAAEGAAB-ZpLKoid3RpHGgeoSzDJmAAAAAF3WAAA=
  entities:
  - device_id: Birthdays
    end_offset: 24
    name: Birthdays
    start_offset: 0
    track: false
- cal_id: AAMkADg5NmZmM2QwLTQ0ZGQtNDA1Zi1iZmRkLWNkMWFjZmI1NTVlNABGAAAAAAD29fpetT5CT6wPo-7_C-fEBwB-ZpLKoid3RpHGgeoSzDJmAAAAAAEGAAB-ZpLKoid3RpHGgeoSzDJmAAAAAF3XAAA=
  entities:
  - device_id: Birthdays
    end_offset: 24
    name: Birthdays
    start_offset: 0
    track: false
- cal_id: AAMkADg5NmZmM2QwLTQ0ZGQtNDA1Zi1iZmRkLWNkMWFjZmI1NTVlNABGAAAAAAD29fpetT5CT6wPo-7_C-fEBwB-ZpLKoid3RpHGgeoSzDJmAAAAAAEGAAB-ZpLKoid3RpHGgeoSzDJmAAAAAF3YAAA=
  entities:
  - device_id: Holidays in Australia
    end_offset: 24
    name: Holidays in Australia
    start_offset: 0
    track: false
- cal_id: AAMkADg5NmZmM2QwLTQ0ZGQtNDA1Zi1iZmRkLWNkMWFjZmI1NTVlNABGAAAAAAD29fpetT5CT6wPo-7_C-fEBwB-ZpLKoid3RpHGgeoSzDJmAAAAAAEGAAB-ZpLKoid3RpHGgeoSzDJmAASoniKqAAA=
  entities:
  - device_id: all
    name: Family all
    track: true
    start_offset: 0
    end_offset: 168
  - device_id: nick
    name: Nick
    track: true
    start_offset: 0
    end_offset: 168
    search: 'Nick:'
  - device_id: elle
    name: Elle
    track: true
    start_offset: 0
    end_offset: 168
    search: 'Elle:'
  - device_id: aria
    name: Aria
    track: true
    start_offset: 0
    end_offset: 168
    search: 'Aria:'
  - device_id: eden
    name: Eden
    track: true
    start_offset: 0
    end_offset: 168
    search: 'Eden:'
  - device_id: shared
    name: Family shared
    track: true
    start_offset: 0
    end_offset: 168
    exclude:
    - 'Nick:'
    - 'Elle:'
    - 'Aria:'
    - 'Eden:'
